spring:
  liquibase:
    enabled: on
    change-log: db/master.yml

  datasource:
    url: jdbc:mysql://localhost:3306/career_bridge
    username: root
    password:

token:
  signIn:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351

application:
  security:
    jwt:
      expiration: 1728000000
      refresh-token:
        expiration: 1728000000
upload:
  dir:
    path: ./src/main/resources/static/profile-images