package com.example.carrer_bridge.domain.enums;

public enum PermissionType {
    VIEW_CANDIDATURE, CREATE_CANDIDATURE, UPDATE_CANDIDATURE, DELETE_CANDIDATURE,
    VIEW_COMMUNICATION, CREATE_COMMUNICATION, UPDATE_COMMUNICATION, DELETE_COMMUNICATION,
    VIEW_COMPANY, CREATE_COMPANY, UPDATE_COMPANY, DELETE_COMPANY,
    VIEW_CITY, CREATE_CITY, UPDATE_CITY, DELETE_CITY,
    VIEW_EDUCATION, CREATE_EDUCATION, UPDATE_EDUCATION, DELETE_EDUCATION,
    VIEW_EXPERIENCE, CREATE_EXPERIENCE, UPDATE_EXPERIENCE, DELETE_EXPERIENCE,
    VIEW_JOB_OPPORTUNITY, CREATE_JOB_OPPORTUNITY, UPDATE_JOB_OPPORTUNITY, DELETE_JOB_OPPORTUNITY,
    VIEW_PERMISSION, CREATE_PERMISSION, UPDATE_PERMISSION, DELETE_PERMISSION,
    VIEW_ROLE, CREATE_ROLE, UPDATE_ROLE, DELETE_ROLE,
    VIEW_ROLE_PERMISSION, CREATE_ROLE_PERMISSION, UPDATE_ROLE_PERMISSION, DELETE_ROLE_PERMISSION,
    VIEW_SKILL, CREATE_SKILL, UPDATE_SKILL, DELETE_SKILL,
    VIEW_TRAINING, CREATE_TRAINING, UPDATE_TRAINING, DELETE_TRAINING,
    VIEW_USER, CREATE_USER, UPDATE_USER, DELETE_USER,
    VIEW_USER_PROFILE, CREATE_USER_PROFILE, UPDATE_USER_PROFILE, DELETE_USER_PROFILE

}
